name: Capture Webpage Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Capture Screenshot
        run: node capture-screenshot.js

      - name: Upload Screenshot to S3
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            aws s3 cp screenshot.png s3://np-screenshot/screenshot.png