name: Capture Webpage Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Capture Screenshot
        run: node capture-screenshot.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
